### ISSUE TITLE
Hide helmet option

### ISSUE THREAD

**Issue by xSlysoft** [equirs/fashionscape-plugin#11]
Hello, I was hesitant to open this issue/request as it might be beyond the scope of this plugin, but I use this plugin sometimes to combat gracefulscape while skilling and sometimes I just want no helmet.

It's also might be possible to do this on the latest version, but the version on plugin hub is only 1.1.2 and I can't figure out a way to install the latest version from github (if it is even possible).

**Comment by equirs** [comment]
If you have IntelliJ, you can always clone the repo and run the new versions yourself by running the only test in the project. But yeah, this will be possible with version 1.1.4. I'm sort of waiting on some changes to the RuneLite API so that it can be made available... sorry it's taking so long.

**Comment by equirs** [comment]
Possible now in version 1.1.3
