### ISSUE TITLE
"Base" option missing?

### ISSUE THREAD

**Issue by Lorenso0** [equirs/fashionscape-plugin#14]
I can't seem to find the "Base" option anywhere, has it been disabled at the moment?

![Base](https://user-images.githubusercontent.com/9676081/114138810-7404de00-990e-11eb-83b0-476c5d60f5b6.png)

**Comment by equirs** [comment]
This feature is only available in version 1.1.4, which isn't released yet. 1.1.2 is the one on the plugin hub.
