### ISSUE TITLE
Spirit angler headband is broken

### ISSUE THREAD

**Issue by xSlysoft** [equirs/fashionscape-plugin#19]
When trying on the Spirit angler headband, the head completely disappears. I think it also has a messed up animation when harpooning but it's hard to tell since the head is invisible.

![image](https://user-images.githubusercontent.com/42144975/116746667-dbbcbf00-a9ca-11eb-9ba0-79b3540d605a.png)

**Comment by equirs** [comment]
I'm aware of this one and a few other newer items. I have to specify these manually and am waiting on the plugin hub to approve an open PR, but it'll be resolved once that merges.
