### ISSUE TITLE
Plugin changing hair on login

### ISSUE THREAD

**Issue by xSlysoft** [equirs/fashionscape-plugin#25]
When logging out of the game while wearing a headpiece that covers the entire head and logging back in, the plugin is not registering the correct hairstyle. 

Removing the actual armor piece (in this case, unequipping graceful hood) will update the hairstyle to the correct one, but any time I log out and back into the game with a full face headpiece on and apply a fashionscape that shows the hair will show the wrong hairstyle.

I have even tried completely uninstalling the extension and reinstalling it in case it had somehow saved some weird default base kit to use when the plugin couldn't see the actual hair slot, but it didn't fix it.

![image](https://user-images.githubusercontent.com/42144975/118362606-222f2380-b55e-11eb-8a0c-c16a69229c9a.png)

**Comment by xSlysoft** [comment]
I just re-read the FAQ and realized that this is probably intended behavior, so rather than a bug perhaps this can be a feature enhancement that allows the plugin to cache a default base kit to use. Not really sure how feasible that would be though.

**Comment by equirs** [comment]
Right, there will always be cases where the plugin can't tell what your actual hairstyle is. I think saving that base info to the config would at least make it so that this happens less often, so I'll implement that.

I also wonder if there's a better way of communicating that this is what's happening since it's obviously kind of confusing. Maybe some sort of game message or warning text in the plugin panel.

**Comment by xSlysoft** [comment]
I think the FAQ adequately explains why it happens, it's just a case of RTFM.

A config module would definitely work, I have sort of worked around it by saving hairstyles to the fashion outfits, but obviously it doesn't work in all cases as any fashion set or item equipped that covers the head overwrites the hair slot. Caching the default base kit would obviously impact people who use multiple characters, but there's no real way to work around every single edge case.

As long as the base config was optional or defaulted to the current functionality those players wouldn't really be impacted.

**Comment by equirs** [comment]
I ended up adding some warnings in the panel when this kind of thing happens, and I've made it happen much less often by saving more info to the plugin's config.
