### ISSUE TITLE
Decorative Swords (Castle War) idle animation

### ISSUE THREAD

**Issue by OldmanOstentatio** [equirs/fashionscape-plugin#54]
Dear high priests of fashion,
Just a small little thing: it would seem that the decorative swords from Castle War use a different standard/idle animation when equipped through the plugin than when regularly equipped, as they are held upright like a Blurite sword instead of being held straight ahead. I checked with the OSRS Wiki discord, where the venerated Andmcadams was able to tell me they use the 808 pose animation rather than the 809 pose the Blurite sword uses. It could be misassigned in the plugin, so I thought you should know.
With the expression of my deepest gratitude for this lovely plugin, I remain,
 – Ostentatio

**Comment by equirs** [comment]
Hey, I think you're right. I probably have made a few other mistakes on the idle anims in the plugin as I went through them pretty hastily. Fix will be applied when I get the chance. Thanks for filing.

**Comment by equirs** [comment]
Should be fixed not with the latest version, 1.1.17
