### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by AndiManzy** [equirs/fashionscape-plugin#56]
Hi! I love fashionscaping around as a pirate, and i can do an override to have a pirate hook at all times just fine...but i can't have my eyepatch on at all times..
Is there any way with your plugin that an eyepatch can be like, baked into the base skintone somehow?
A few characters (Brundt the Chieftan for example) have a patch with random helmets that we don't have access to, which I'm sure is it's own item id, but i didn't know how possible it might be to have an eyepatch on at all times, and any head slot item worn would just go on as usual to complement it.

**Comment by equirs** [comment]
The only way to make that possible would be to load in custom-made models and mess with the way those models are accessed from the cache, which is something I think is not supported in RuneLite, and even if I requested it, would probably not happen.

The NPCs in the game usually have much less complex models, and the equipment they have on may be inseparable from the rest of them. They don't have item ids as far as I know.

I think it's a neat idea but it's not somewhere I can realistically take this plugin.
