### ISSUE TITLE
plugin no longer in plugins list or plugin hub

### ISSUE THREAD

**Issue by Sarashasu** [equirs/fashionscape-plugin#57]
actively used plugin last night (and have been using for months) 

logged in today and it's completely gone.

**Comment by equirs** [comment]
Most likely failed to build from the last runelite update, will take a look when I finish work

**Comment by geheur** [comment]
https://repo.runelite.net/plugins/1.8.33.1/fashionscape/ log file here
```
> Task :compileJava
/tmp/pluginhub-package921256631347546234/fashionscape/repo/src/main/java/eq/uirs/fashionscape/data/ItemInteractions.java:476: error: cannot find symbol
		WEAPON_TO_IDLE.put(ItemID.EVENT_RPG, IdleAnimationID.OVERHEAD_LAUNCHER);
		                         ^
  symbol:   variable EVENT_RPG
  location: class ItemID
1 error
```
item name changed this update.

**Comment by equirs** [comment]
We're back
