### ISSUE TITLE
Max Hit & Fashionscape problem

### ISSUE THREAD

**Issue by Pherodactyl** [equirs/fashionscape-plugin#60]
So I'm not sure which plugin is causing the issue, or whether it's even that big of a deal, so I'm just going to post this for both plugins. Essentially the problem is that the Fashionscape plugin changes the max hit calculation to the gear shown with Fashionscape. Not sure why or how it's happening all I know is that when I turn off the Fashionscape plugin my max hit goes back to what it should be.

**Comment by equirs** [comment]
I don't think there's anything I can do about this, since the plugin changes player model ids, and if that plugin is using those, it'll mess with your max hit. Nothing I can change on my end
