### ISSUE TITLE
FashionScape plugin is incompatible (Needs update by Author)

### ISSUE THREAD

**Issue by Donic40** [equirs/fashionscape-plugin#65]
As the title says, I logged in today to find out that my favourite plugin is no longer compatible.
It says it requires an update by the author.

I'm writing here in hopes that the author sees it and fixes it.

Thank you!

**Comment by Donic40** [comment]
Thank you for the quick reply! Will be looking forward to it being fixed!

**Comment by Donic40** [comment]
Thank you!! You're the best, that was so quick <3

**Comment by Popedigoz** [comment]
> Thanks for reporting. Not super active in game, so I was unaware it was broken. Will work on a fix as soon as I'm able to

@equirs it's broken again

**Comment by equirs** [comment]
Hi, it's not broken again; I submitted a fix here https://github.com/runelite/plugin-hub/pull/5413 and it hasn't been approved yet. Looks like the RuneLite folks have quite a few updates to hub plugins currently waiting for approval.

**Comment by equirs** [comment]
Appears to be working again
