### ISSUE TITLE
fashion scape not working

### ISSUE THREAD

**Issue by jesusizk1ng** [equirs/fashionscape-plugin#70]
maybe i just have to wait for it to be updated as the game was just updated

**Comment by equirs** [comment]
Dupe of #69 

Game update broke it, yeah. Working on a fix now

**Comment by jesusizk1ng** [comment]
> Dupe of #69
> 
> Game update broke it, yeah. Working on a fix now

ok got it thank you, is there a place that will give updates on when it will be back up

**Comment by equirs** [comment]
If you had it enabled before it went down, it'll be back up and working once the fix is merged. The fixes I have to make are not as straightforward as globally replacing a number, as I initially thought.

**Comment by equirs** [comment]
should be back online now, next time you start RuneLite
